// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpfitionfrabfzlcapum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZml0aW9uZnJhYmZ6bGNhcHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTk5ODgsImV4cCI6MjA1Njg5NTk4OH0.hxfU70in-zdKypXvNVHO2bV1_I71Cd2ShfASIFaoP0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);